<?php
/**
 * Created by PhpStorm.
 * Date: 08/06/2020
 * Time: 11:05
 */
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5eddee432b60e',
        'title' => 'Entreprises',
        'fields' => array(
            array(
                'key' => 'field_5eb0052891685',
                'label' => 'Présentation graphique',
                'name' => 'presentation_graphique',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                        array(
                            'key' => 'field_5eec796496745',
                            'label' => 'Description - Icône 1',
                            'name' => 'titre_representation_1',
                            'type' => 'text',
                            'instructions' => '<i class="icon-svgcolor thermometer-color"><img src="'.get_template_directory_uri().'/assets/svg/thermometer-color.svg"></i>',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Luttez contre les changements climatiques',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5eec796496746',
                            'label' => 'Description - Icône 2',
                            'name' => 'titre_representation_2',
                            'type' => 'text',
                            'instructions' => '<i class="icon-svgcolor realisation-color"><img src="'.get_template_directory_uri().'/assets/svg/erosion-color.svg"></i>',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Luttez contre l’érosion des sols',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5eec796496747',
                            'label' => 'Description - Icône 3',
                            'name' => 'titre_representation_3',
                            'type' => 'text',
                            'instructions' => '<i class="icon-svgcolor erosion-color"><img src="'.get_template_directory_uri().'/assets/svg/biodiversite-color.svg"></i>',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Renforcez la biodiversité',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    array(
                        'key' => 'field_5eec796496748',
                        'label' => 'Description - Icône 4',
                        'name' => 'titre_representation_4',
                        'type' => 'text',
                        'instructions' => '<i class="icon-svgcolor erosion-color"><img src="'.get_template_directory_uri().'/assets/svg/rural-emancipation-color.svg"></i>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Participez à l’émancipation des communautés rurales',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5eec796496749',
                        'label' => 'Description - Icône 5',
                        'name' => 'titre_representation_5',
                        'type' => 'text',
                        'instructions' => '<i class="icon-svgcolor erosion-color"><img src="'.get_template_directory_uri().'/assets/svg/builder-color.svg"></i>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Développez les entrepreneurs Malagasy',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                )
            ),
            array(
                'key' => 'field_5eddeec3cbaf2',
                'label' => 'contenu de l\'entreprise',
                'name' => 'contenu_de_lentreprise',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5eddef30cbaf3',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '256',
                    ),
                    array(
                        'key' => 'field_5eddef79cbaf4',
                        'label' => 'Icon représentatif',
                        'name' => 'icon_representatif',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'print-ecological'=>'<i class="icobnd-print-ecological"></i>',
                            'combine-products'=>'<i class="icobnd-combine-products"></i>',
                            'vegetaliser'=>'<i class="icobnd-vegetaliser"></i>',
                            'tree-up' => '<i class="icobnd-tree-up"></i>',
                            'trees-2' => '<i class="icobnd-trees-2"></i>',
                            'noforest' => '<i class="icobnd-noforest"></i>',
                            'tree_money' => '<i class="icobnd-tree_money"></i>',
                            'leaves' => '<i class="icobnd-leaves"></i>',
                            'wood' => '<i class="icobnd-wood"></i>',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_5eddefddcbaf5',
                        'label' => 'Decription',
                        'name' => 'decription',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5eddf030cbaf6',
                        'label' => 'Image',
                        'name' => 'image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5eddf0c9cbafb',
                        'label' => 'Exemple de partenariat',
                        'name' => 'exemple_de_partenaies',
                        'type' => 'relationship',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'partenaire',
                        ),
                        'taxonomy' => '',
                        'filters' => array(
                            0 => 'post_type',
                        ),
                        'elements' => '',
                        'min' => '',
                        'max' => '',
                        'return_format' => 'object',
                    ),
                    array(
                        'key' => 'field_5eddf042cbaf7',
                        'label' => 'Pictogrammes',
                        'name' => 'pictogrammes',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5eddf056cbaf8',
                                'label' => 'Picto',
                                'name' => 'picto',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'communication-color'=>'<i class="icon-svgcolor communication-color"><img src="'.get_template_directory_uri().'/assets/svg/communication-color.svg"></i>',
                                    'conception-color'=>'<i class="icon-svgcolor conception-color"><img src="'.get_template_directory_uri().'/assets/svg/conception-color.svg"></i>',
                                    'croissance-color'=>'<i class="icon-svgcolor croissance-color"><img src="'.get_template_directory_uri().'/assets/svg/croissance-color.svg"></i>',
                                    'thermometer-color'=>'<i class="icon-svgcolor thermometer-color"><img src="'.get_template_directory_uri().'/assets/svg/thermometer-color.svg"></i>',
                                    'evaluation-color'=>'<i class="icon-svgcolor evaluation-color"><img src="'.get_template_directory_uri().'/assets/svg/evaluation-color.svg"></i>',
                                    'realisation-color'=>'<i class="icon-svgcolor realisation-color"><img src="'.get_template_directory_uri().'/assets/svg/realisation-color.svg"></i>',
                                    'development-durable-color.svg'=>'<i class="icon-svgcolor developpement-durable-color"><img src="'.get_template_directory_uri().'/assets/svg/development-durable-color.svg"></i>',
                                    'erosion-color'=>'<i class="icon-svgcolor erosion-color"><img src="'.get_template_directory_uri().'/assets/svg/erosion-color.svg"></i>',
                                    'biodiversite-color'=>'<i class="icon-svgcolor biodiversite-color"><img src="'.get_template_directory_uri().'/assets/svg/biodiversite-color.svg"></i>',
                                    'rural-emancipation-color'=>'<i class="icon-svgcolor rural-emancipation-color"><img src="'.get_template_directory_uri().'/assets/svg/rural-emancipation-color.svg"></i>',
                                    'builder-color'=>'<i class="icon-svgcolor builder-color"><img src="'.get_template_directory_uri().'/assets/svg/builder-color.svg"></i>',
                                    'agroforestry-color'=>'<i class="icon-svgcolor builder-color"><img src="'.get_template_directory_uri().'/assets/svg/agroforestry-color.svg"></i>',
                                    'urban-forest-color'=>'<i class="icon-svgcolor urban-forest-color"><img src="'.get_template_directory_uri().'/assets/svg/urban-forest-color.svg"></i>',
                                    'vegetable-garden-color'=>'<i class="icon-svgcolor vegetable-garden-color"><img src="'.get_template_directory_uri().'/assets/svg/vegetable-garden-color.svg"></i>',
                                    'sensibilisation-color'=>'<i class="icon-svgcolor sensibilisation-color"><img src="'.get_template_directory_uri().'/assets/svg/sensibilisation-color.svg"></i>',
                                    'ethical-supplier-color'=>'<i class="icon-svgcolor ethical-supplier-color"><img src="'.get_template_directory_uri().'/assets/svg/ethical-supplier-color.svg"></i>',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                                'save_other_choice' => 0,
                            ),
                            array(
                                'key' => 'field_5eddf066cbaf9',
                                'label' => 'Titre',
                                'name' => 'titre',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '256',
                            ),
                            array(
                                'key' => 'field_5eddf07fcbafa',
                                'label' => 'Description',
                                'name' => 'description',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                        ),
                    ),

                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/entreprises.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;