<?php
/**
 * Created by PhpStorm.
 * Date: 08/06/2020
 * Time: 14:18
 */
//mp(uniqid());
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5edf1c884f5b8',
        'title' => 'Informations sur la page Particulier',
        'fields' => array(
            array(
                'key' => 'field_5ec4bf836dad8',
                'label' => 'Description par icône',
                'name' => 'icones_en_tete',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(


                    //icone  1
                    array(
                        'key' => 'field_5ed0c21ba1d6a',
                        'label' => 'Icone 1',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),

                    array(
                        'key' => 'field_5eb3535172a7c',
                        'label' => '',
                        'name' => 'bondy_icone_picto_1',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'phone-screen-color'=>'<i class="icon-svgcolor phone-screen-color"><img src="'.get_template_directory_uri().'/assets/svg/phone-screen-color.svg"></i>',
                            'handshake'=>'<i class="icon-svgcolor solution-owner-color"><img src="'.get_template_directory_uri().'/assets/svg/solution-owner-color.svg"></i>',
                            'realisation-color'=>'<i class="icon-svgcolor realisation-color"><img src="'.get_template_directory_uri().'/assets/svg/realisation-color.svg"></i>',
                            'recolte-color'=>'<i class="icon-svgcolor recolte-color"><img src="'.get_template_directory_uri().'/assets/svg/recolte-color.svg"></i>',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,

                    ),

                    array(
                        'key' => 'field_5eeb0353546d918b',
                        'label' => 'Description',
                        'name' => 'description_icone_1',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => 'br',
                    ),

                    //icone 2
                    
                    array(
                        'key' => 'field_5ef098b96f838',
                        'label' => 'Icone 2',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),

                    array(
                        'key' => 'field_5ef09a49212b7',
                        'label' => '',
                        'name' => 'bondy_icone_picto_2',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(                      
                            'phone-screen-color'=>'<i class="icon-svgcolor phone-screen-color"><img src="'.get_template_directory_uri().'/assets/svg/phone-screen-color.svg"></i>',
                            'handshake'=>'<i class="icon-svgcolor solution-owner-color"><img src="'.get_template_directory_uri().'/assets/svg/solution-owner-color.svg"></i>',
                            'realisation-color'=>'<i class="icon-svgcolor realisation-color"><img src="'.get_template_directory_uri().'/assets/svg/realisation-color.svg"></i>',
                            'recolte-color'=>'<i class="icon-svgcolor recolte-color"><img src="'.get_template_directory_uri().'/assets/svg/recolte-color.svg"></i>',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,

                    ),

                    array(
                        'key' => 'field_5eeb0946d918a',
                        'label' => 'Description',
                        'name' => 'description_icone_2',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => 'br',
                    ),

                     //icone  3
                    array(
                        'key' => 'field_5ef09a6377660',
                        'label' => 'Icone 3',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),

                    array(
                        'key' => 'field_5ef09afd2b69a',
                        'label' => '',
                        'name' => 'bondy_icone_picto_3',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(                        
                            'phone-screen-color'=>'<i class="icon-svgcolor phone-screen-color"><img src="'.get_template_directory_uri().'/assets/svg/phone-screen-color.svg"></i>',
                            'handshake'=>'<i class="icon-svgcolor solution-owner-color"><img src="'.get_template_directory_uri().'/assets/svg/solution-owner-color.svg"></i>',
                            'realisation-color'=>'<i class="icon-svgcolor realisation-color"><img src="'.get_template_directory_uri().'/assets/svg/realisation-color.svg"></i>',
                            'recolte-color'=>'<i class="icon-svgcolor recolte-color"><img src="'.get_template_directory_uri().'/assets/svg/recolte-color.svg"></i>',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,

                    ),

                    array(
                        'key' => 'field_5ef09b2555686',
                        'label' => 'Description',
                        'name' => 'description_icone_3',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => 'br',
                    ),


                     //icone  4
                    array(
                        'key' => 'field_5ef09b4651858',
                        'label' => 'Icone 4',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),

                    array(
                        'key' => 'field_5ef09b5b646cb',
                        'label' => '',
                        'name' => 'bondy_icone_picto_4',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'phone-screen-color'=>'<i class="icon-svgcolor phone-screen-color"><img src="'.get_template_directory_uri().'/assets/svg/phone-screen-color.svg"></i>',
                            'handshake'=>'<i class="icon-svgcolor solution-owner-color"><img src="'.get_template_directory_uri().'/assets/svg/solution-owner-color.svg"></i>',
                            'realisation-color'=>'<i class="icon-svgcolor realisation-color"><img src="'.get_template_directory_uri().'/assets/svg/realisation-color.svg"></i>',
                            'recolte-color'=>'<i class="icon-svgcolor recolte-color"><img src="'.get_template_directory_uri().'/assets/svg/recolte-color.svg"></i>',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,

                    ),

                    array(
                        'key' => 'field_5ef09b7090482',
                        'label' => 'Description',
                        'name' => 'description_icone_4',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => 'br',
                    ),
                ),
            ),

             array(
                'key' => 'field_5fa1fb86f7b6b',
                'label' => 'Diverses solutions adaptées à vos besoins',
                'name' => 'titre_diverses_solutions_adaptees',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '256',
            ),
            
            array(
                'key' => 'field_5edf64414914a',
                'label' => 'Informations sur les diverses solutions adaptées à vos besoins',
                'name' => 'contenu_particulier',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 4,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(

                    array(
                    'key' => 'field_5ef1ac1a32124',
                    'label' => 'Onglet',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    ),

                    array(
                        'key' => 'field_5edf1cabe51a3',
                        'label' => 'Titre onglet',
                        'name' => 'titre',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                         'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'wysiwyg_titre_bondy',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5edf1cbae51a4',
                        'label' => 'Icône représentatif de l\'onglet',
                        'name' => 'icon_representatif',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'develop-land'=>'<i class="icobnd-develop-land"></i>',
                            'volunteers'=>'<i class="icobnd-volunteers"></i>',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,

                    ),


                    array(
                    'key' => 'field_5ef1ab6f08daf',
                    'label' => 'Contenu du bloc',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    ),

                    array(
                        'key' => 'field_5edf1ce4e51a5',
                        'label' => 'Aucun (NA) / Avec contenu',
                        'name' => 'contenu',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Oui' => 'Oui',
                            'Non' => 'Non',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),


                    array(
                        'key' => 'field_5edf64414999a',
                        'label' => '',
                        'name' => 'block_contenu',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5edf1ce4e51a5',
                                        'operator' => '==contains',
                                        'value' => 'Oui',
                                    ),
                                ),
                            ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                            'key' => 'field_5edf4c6de51a6',
                            'label' => 'Titre du bloc',
                            'name' => 'titre_du_bloc_contenu',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '256',
                        ),
                        array(
                            'key' => 'field_5edf4dc1e51a7',
                            'label' => 'Description du bloc',
                            'name' => 'texte_du_bloc',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                        array(
                            'key' => 'field_5edf4e1ce51a8',
                            'label' => 'Position de l\'image du bloc',
                            'name' => 'position_de_limage',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'gauche' => 'gauche',
                                'droite' => 'droite',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => '',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                            'save_other_choice' => 0,
                        ),
                        array(
                            'key' => 'field_5edf4e69e51a9',
                            'label' => 'Image du bloc',
                            'name' => 'image_du_bloc_de_contenu',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'id',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array(
                            'key' => 'field_5edf4eb7e51aa',
                            'label' => 'Lien du bouton contactez-nous',
                            'name' => 'lien_bouton_contactez_nous',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '256',
                        ),
                        /*array(
                            'key' => 'field_5edf4f8fe51ab',
                            'label' => 'Nom du bouton vert',
                            'name' => 'titre_du_bouton_vert',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '256',
                        ),
                        array(
                            'key' => 'field_5ef1af10b9956',
                            'label' => 'Lien du bouton vert',
                            'name' => 'lien_du_bouton_vert',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => '',
                            'taxonomy' => '',
                            'allow_null' => 0,
                            'allow_archives' => 0,
                            'multiple' => 0,
                        ),*/
                    )),
                    array(
                        'key' => 'field_5edf4fc8e51ad',
                        'label' => 'Nom du bouton',
                        'name' => 'titre_du_bouton',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5edf1ce4e51a5',
                                    'operator' => '==contains',
                                    'value' => 'Non',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '256',
                    ),
                    array(
                        'key' => 'field_5edf4febe51ae',
                        'label' => 'Lien du bouton',
                        'name' => 'lien_du_bouton',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5edf1ce4e51a5',
                                    'operator' => '==contains',
                                    'value' => 'Non',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => '',
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'allow_archives' => 0,
                        'multiple' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/particulier.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
    ));

endif;