<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5eb004ff91130',
        'title' => 'DÉTAILS ACCUEIL',
        'fields' => array(
            array(
                'key' => 'field_5eb00528916b0',
                'label' => 'LANDING PAGE',
                'name' => 'bienvenue',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5efee11e45940',
                        'label' => 'Image de bienvenue gris',
                        'name' => 'image_de_bienvenue_gris',
                        'type' => 'image',
                        'instructions' => 'Taille de \'image optimale 1920 x 853',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5eb00573916b1',
                        'label' => 'Image de bienvenue',
                        'name' => 'image_de_bienvenue',
                        'type' => 'image',
                        'instructions' => 'Taille de \'image optimale 1920 x 853',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5eb006a6916b2',
                        'label' => 'Texte de bienvenue',
                        'name' => 'texte_de_bienvenue',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '70',
                    ),
                ),
            ),
            array(
                'key' => 'field_5eb11ca62a6ce',
                'label' => 'PROJETS BONDY',
                'name' => 'projets_bondy',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ed0c38520c55',
                        'label' => 'Titre',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb11cb92a6cf',
                        'label' => 'Titre projet bondy',
                        'name' => 'titre_home_projet_bondy',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'wysiwyg_titre_bondy',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5eb11cfc2a6d0',
                        'label' => 'Sous titre projet bondy',
                        'name' => 'sous_titre_home_projet_bondy',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '70',
                    ),
                    array(
                        'key' => 'field_5ed0c44fea75a',
                        'label' => 'Mise en avant',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb11d5d2a6d1',
                        'label' => 'Projets mise en avant',
                        'name' => 'projets_mise_en_avant',
                        'type' => 'relationship',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'projet',
                        ),
                        'taxonomy' => '',
                        'filters' => array(
                            0 => 'post_type',
                        ),
                        'elements' => '',
                        'min' => '',
                        'max' => '',
                        'return_format' => 'id',
                    ),
                ),
            ),
            array(
                'key' => 'field_5eb8f3a7f71fa',
                'label' => 'SAVEZ-VOUS PLANTER DES ARBRES',
                'name' => 'savez_vous_planter',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ed0c4cfd383b',
                        'label' => 'Titre',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb8f40af71fb',
                        'label' => 'Titre',
                        'name' => 'titre_savez_vous_planter',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'wysiwyg_titre_bondy',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5eb8f435f71fc',
                        'label' => 'Sous-titre',
                        'name' => 'sous_titre_savez_vous_planter',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ed0c51938733',
                        'label' => 'Description',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb8f473f71fd',
                        'label' => '',
                        'name' => 'description_savez_vous_planter',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5ed0c567f1b9e',
                        'label' => 'Rubriques',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb90d1e89b8a',
                        'label' => '',
                        'name' => 'rubriques',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => 'field_5eb9250389b8b',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Ajouter une rubrique',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5eb9250389b8b',
                                'label' => 'Titre rubrique',
                                'name' => 'titre_rubrique',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '70',
                            ),
                            array(
                                'key' => 'field_5eb9251389b8c',
                                'label' => 'Description rubrique',
                                'name' => 'description_rubrique',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5eb9252989b8d',
                                'label' => 'Icon rubrique',
                                'name' => 'icon_rubrique',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'icobnd-environnemental' => '<i class="icobnd-environnemental"></i>',
                                    'icobnd-economique' => '<i class="icobnd-economique"></i>',
                                    'icobnd-fruits' => '<i class="icobnd-fruits"></i>',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                                'save_other_choice' => 0,
                            ),
                            array(
                                'key' => 'field_5eb93d24c5e9a',
                                'label' => 'Mots clés rubrique',
                                'name' => 'mots_cles_rubrique',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => 'field_5eb945e8a8584',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Ajouter mots clés',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5eb945c5a8583',
                                        'label' => 'Icon mots clés',
                                        'name' => 'icon_mots_cles',
                                        'type' => 'radio',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'cycles-water' => '<i class="icobnd-cycles-water"></i>',
                                            'puits-carbone' => '<i class="icobnd-puits-carbone"></i>',
                                            'erosion' => '<i class="icobnd-erosion"></i>',
                                            'fertility' => '<i class="icobnd-fertility"></i>',
                                            'maki' => '<i class="icobnd-maki"></i>',
                                            'climat-urban' => '<i class="icobnd-climat-urban"></i>',
                                            'thermometer' => '<i class="icobnd-thermometer"></i>',
                                            'catastroph' => '<i class="icobnd-catastroph"></i>',
                                            'vegetaliser' => '<i class="icobnd-vegetaliser"></i>',
                                            'apple-2' => '<i class="icobnd-apple-2"></i>',
                                            'tree_money' => '<i class="icobnd-tree_money"></i>',
                                            'airplane' => '<i class="icobnd-airplane"></i>',
                                            'firewood' => '<i class="icobnd-firewood"></i>',
                                            'hand-fruit' => '<i class="icobnd-hand-fruit"></i>',
                                            'medicinal-vertue' => '<i class="icobnd-medicinal-vertue"></i>',
                                            'builder' => '<i class="icobnd-builder"></i>',
                                        ),
                                        'allow_null' => 0,
                                        'other_choice' => 0,
                                        'default_value' => '',
                                        'layout' => 'horizontal',
                                        'return_format' => 'value',
                                        'save_other_choice' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5eb945e8a8584',
                                        'label' => 'Texte mots clés',
                                        'name' => 'texte_mots_cles',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '70',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_5eba38464b397',
                'label' => 'ENGAGEZ VOTRE ENTREPRISE DE MANIÈRE DURABLE ET ÉTHIQUE !',
                'name' => 'engager_votre_entreprise',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5eba38644b398',
                        'label' => 'Bannière engager votre entreprise',
                        'name' => 'banniere_engager_entreprise',
                        'type' => 'image',
                        'instructions' => 'Taille de l\'image optimale 1920 x 853',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5eba38ad4b399',
                        'label' => 'Titre engager votre entreprise',
                        'name' => 'titre_engager_votre_entreprise',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '70',
                    ),
                    array(
                        'key' => 'field_5eba38c94b39a',
                        'label' => 'Sous-titre engager votre entreprise',
                        'name' => 'sous_titre_engager_votre_entreprise',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5eba38db4b39b',
                        'label' => 'Texte bouton engager votre entreprise',
                        'name' => 'texte_bouton_engager_votre_entreprise',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '70',
                    ),
                    array(
                        'key' => 'field_5ef3564ad35c1',
                        'label' => 'Lien bouton engager votre entreprise',
                        'name' => 'lien_bouton_engager_votre_entreprise',
                        'type' => 'page_link',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                        ),
                        'taxonomy' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'allow_archives' => 1,
                    ),
                ),
            ),
            /*array(
                'key' => 'field_5eba91aeb7180',
                'label' => 'Ils parlent de nous',
                'name' => 'ils_parlent_de_nous',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5eb8fb86e7b6b',
                        'label' => 'Titre du bloc',
                        'name' => 'sous-titre_du_bloc',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'wysiwyg_titre_bondy',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5eb8fb9be7b6c',
                        'label' => 'Description du bloc',
                        'name' => 'description_du_bloc',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5eb55e2db0e4e',
                        'label' => 'Relation temoignage',
                        'name' => 'relation_temoignage',
                        'type' => 'relationship',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'temoignage',
                        ),
                        'taxonomy' => '',
                        'filters' => array(
                            0 => 'post_type',
                        ),
                        'elements' => '',
                        'min' => '',
                        'max' => '',
                        'return_format' => 'id',
                    ),
                ),
            ),*/
            array(
                'key' => 'field_5eba92621e886',
                'label' => 'IL PARLENT DE NOUS & TOUT LE MONDE EN PARLE',
                'name' => 'tout_le_monde_en_parle',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ed0c7628e4f4',
                        'label' => 'Titre',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb90a2ca4c89',
                        'label' => '',
                        'name' => 'titre_du_bloc_tout_le_monde_en_parle',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'wysiwyg_titre_bondy',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5ed0c79d7dbff',
                        'label' => 'Description',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb90a72a4c8a',
                        'label' => '',
                        'name' => 'description_du_bloc_tout_le_monde_en_parle',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5ed0c7bb25186',
                        'label' => 'Mise en avant',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb914e40d1d1',
                        'label' => 'Actualité mise en avant',
                        'name' => 'relation_actualite',
                        'type' => 'relationship',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'actualite',
                        ),
                        'taxonomy' => '',
                        'filters' => array(
                            0 => 'post_type',
                        ),
                        'elements' => '',
                        'min' => '',
                        'max' => '',
                        'return_format' => 'id',
                    ),
                ),
            ),
            array(
                'key' => 'field_5eba89fae7d64',
                'label' => 'JE VEUX METTRE EN VALEUR MES TERRAINS',
                'name' => 'mettre_en_valeur',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ed0c8262ba1e',
                        'label' => 'Titre',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eba76492868c',
                        'label' => '',
                        'name' => 'mettre_en_valeur_mes_terrains',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5ed0c84c3ee69',
                        'label' => 'Description',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eba76632868d',
                        'label' => 'Description',
                        'name' => 'description_mettre_en_valeur',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '70',
                    ),
                    array(
                        'key' => 'field_5eba76902868e',
                        'label' => 'En savoir plus',
                        'name' => 'en_savoir_plus',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                    ),
                    array(
                        'key' => 'field_5eba76d82868f',
                        'label' => 'Image du bloc',
                        'name' => 'image_mettre_en_valeur',
                        'type' => 'image',
                        'instructions' => 'Taille de l\'image optimale 1632 x 695',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5eba94a0582c1',
                'label' => 'NOUS SOMMES PRÊTS A CHANGER LE MONDE AVEC VOUS',
                'name' => 'nous_sommes_pret',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5eb8fb86e7b6b',
                        'label' => 'Titre du bloc',
                        'name' => 'sous_titre_nous_sommes_pret',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'wysiwyg_titre_bondy',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/accueil.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
    ));

endif;
