<?php
/**
 * Created by PhpStorm.
 * Date: 06/05/2020
 * Time: 15:46
 */
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5eb2953cb8989',
        'title' => 'DÉCOUVREZ NOS VALEURS',
        'fields' => array(
            array(
                'key' => 'field_5ed0b88163846',
                'label' => 'Titre',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5eb2956072a79',
                'label' => '',
                'name' => 'bondy_banniere_valeurs_titre',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'wysiwyg_titre_bondy',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5ed0b8d477d02',
                'label' => 'Image',
                'name' => '',
                'type' => 'tab',
                'instructions' => 'Taille de l\'image optimale 1632 x 695',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5eb2968572a7a',
                'label' => 'Image de fond',
                'name' => 'bondy_banniere_valeurs_image',
                'type' => 'image',
                'instructions' => 'Taille de l\'image optimale 1632 x 695',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5ed0b9095fad6',
                'label' => 'Valeur ',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5eb297ca72a7b',
                'label' => '',
                'name' => 'bondy_banniere_valeurs',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ed0c21ba1c9a',
                        'label' => 'Picto ',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb2981172a7c',
                        'label' => '',
                        'name' => 'bondy_banniere_valeurs_picto',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'economique'=>'<i class="icobnd-economique"></i>',
                            'exigence'=>'<i class="icobnd-exigence"></i>',
                            'audace'=>'<i class="icobnd-audace"></i>',
                            'cycles-water' => '<i class="icobnd-cycles-water"></i>',
                            'puits-carbone' => '<i class="icobnd-puits-carbone"></i>',
                            'erosion' => '<i class="icobnd-erosion"></i>',
                            'fertility' => '<i class="icobnd-fertility"></i>',
                            'maki' => '<i class="icobnd-maki"></i>',
                            'climat-urban' => '<i class="icobnd-climat-urban"></i>',
                            'thermometer' => '<i class="icobnd-thermometer"></i>',
                            'catastroph' => '<i class="icobnd-catastroph"></i>',
                            'vegetaliser' => '<i class="icobnd-vegetaliser"></i>',
                            'apple-2' => '<i class="icobnd-apple-2"></i>',
                            'tree_money' => '<i class="icobnd-tree_money"></i>',
                            'airplane' => '<i class="icobnd-airplane"></i>',
                            'firewood' => '<i class="icobnd-firewood"></i>',
                            'hand-fruit' => '<i class="icobnd-hand-fruit"></i>',
                            'medicinal-vertue' => '<i class="icobnd-medicinal-vertue"></i>',
                            'builder' => '<i class="icobnd-builder"></i>',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,

                    ),
                    array(
                        'key' => 'field_5ed0c25b7df4c',
                        'label' => 'Titre valeur',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb29bc372a7d',
                        'label' => '',
                        'name' => 'bondy_banniere_valeurs_texte',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '70',
                    ),
                    array(
                        'key' => 'field_5ed0c285acd95',
                        'label' => 'Description',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb29c5572a7e',
                        'label' => '',
                        'name' => 'bondy_banniere_valeurs_texte_description',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/qui-sommes-nous.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
    ));

endif;