<?php
/**
 * Created by PhpStorm.
 * Date: 06/05/2020
 * Time: 15:43
 */
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5eb29dfca67c4',
        'title' => 'LES 3 PILIERS DE BÔNDY',
        'fields' => array(
            array(
                'key' => 'field_5ed0bb6414d7f',
                'label' => 'Titre',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5eb29e3495978',
                'label' => '',
                'name' => 'bondy_banniere_pilier_titre',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'wysiwyg_titre_bondy',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5ed0bb7c8c3c2',
                'label' => 'Description',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5eb29e7295979',
                'label' => '',
                'name' => 'bondy_banniere_pilier_description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5ed0bbaa7d57f',
                'label' => 'Piliers',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5eb29f3f9597a',
                'label' => '',
                'name' => 'bondy_banniere_pilier_valeur',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ed0c08a23d0f',
                        'label' => 'Image',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb29f5e9597b',
                        'label' => 'Image du pilier',
                        'name' => 'bondy_banniere_pilier_valeur_image',
                        'type' => 'image',
                        'instructions' => 'Taille de l\'image optimale 242 x 242',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5ed0c0b56d845',
                        'label' => 'Titre',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb29fa69597c',
                        'label' => 'Titre du pilier',
                        'name' => 'bondy_banniere_pilier_valeur_titre',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '70',
                    ),
                    array(
                        'key' => 'field_5ed0c0d78285a',
                        'label' => 'Description',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5eb3cca407fa3',
                        'label' => 'Description du pilier',
                        'name' => 'bondy_banniere_pilier_valeur_description',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => '5eb52e797e4fe',
                        'label' => 'Description partie 2 du pilier',
                        'name' => 'bondy_banniere_pilier_valeur_description_2',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5eb2a00d9597d',
                        'label' => 'Les pictos du pilier',
                        'name' => 'bondy_banniere_pilier_valeur_picto',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5eb2a0379597e',
                                'label' => 'Picto',
                                'name' => 'bondy_banniere_pilier_valeur_picto_image',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'cycles-water' => '<i class="icobnd-cycles-water"></i>',
                                    'revenu' => '<i class="icobnd-revenu"></i>',
                                    'automatisation' => '<i class="icobnd-automatisation"></i>',
                                    'builder' => '<i class="icobnd-builder"></i>',
                                    'optimize-productivity' => '<i class="icobnd-optimize-productivity"></i>',
                                    'chain' => '<i class="icobnd-chain"></i>',
                                    'waters' => '<i class="icobnd-waters"></i>',
                                    'firewood' => '<i class="icobnd-firewood"></i>',
                                    'construction' => '<i class="icobnd-construction"></i>',
                                    'erosion' => '<i class="icobnd-erosion"></i>',
                                    'puits-carbone' => '<i class="icobnd-puits-carbone"></i>',
                                    'fertility' => '<i class="icobnd-fertility"></i>',
                                    'maki' => '<i class="icobnd-maki"></i>',
                                    'climat-urban' => '<i class="icobnd-climat-urban"></i>',
                                    'thermometer' => '<i class="icobnd-thermometer"></i>',
                                    'catastroph' => '<i class="icobnd-catastroph"></i>',
                                    'vegetaliser' => '<i class="icobnd-vegetaliser"></i>',
                                    'apple-2' => '<i class="icobnd-apple-2"></i>',
                                    'tree_money' => '<i class="icobnd-tree_money"></i>',
                                    'airplane' => '<i class="icobnd-airplane"></i>',
                                    'hand-fruit' => '<i class="icobnd-hand-fruit"></i>',
                                    'medicinal-vertue' => '<i class="icobnd-medicinal-vertue"></i>',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                                'save_other_choice' => 0,
                            ),
                            array(
                                'key' => 'field_5eb2a07b9597f',
                                'label' => 'Titre du picto',
                                'name' => 'bondy_banniere_pilier_valeur_picto_titre',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '70',
                            ),
                        ),
                    ),

                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/qui-sommes-nous.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
    ));

endif;
